In [1]:
import numpy as np

In [2]:
x_size, y_size = 5, 11
a = 0.2

In [3]:
# x_size, y_size = 10, 21
# a = 0.1

In [4]:
# x_size, y_size = 20, 41
# a = 0.05

In [5]:
# x_size, y_size = 40, 81
# a = 0.025

In [6]:
x_arr = np.arange(x_size)
y_arr = np.arange(y_size)
grid = np.zeros((x_size, y_size,), dtype=np.float64)
x_grid = grid.copy()
y_grid = grid.copy()
x_grid[x_arr, :] = x_arr[:, None] * a
y_grid[:, y_arr] = y_arr * a
display(x_grid, y_grid)

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6],
       [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]])

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]])

In [7]:
in_set = y_grid == y_grid[0, 0]
out_set = y_grid == y_grid[0, -1]
display(in_set, out_set)

array([[ True, False, False, False, False, False, False, False, False,
        False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False]])

array([[False, False, False, False, False, False, False, False, False,
        False,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True]])

In [8]:
x_lgrid = np.zeros((x_size, y_size, 2,), dtype=np.float64)
y_lgrid = np.zeros((x_size, y_size, 2,), dtype=np.float64)
x_lgrid[:, :, 0] = x_grid + 0.5 * a
x_lgrid[:, :, 1] = x_grid
y_lgrid[:, :, 0] = y_grid
y_lgrid[:, :, 1] = y_grid + 0.5 * a
display(x_lgrid[:, :, 0], x_lgrid[:, :, 1])
display(y_lgrid[:, :, 0], y_lgrid[:, :, 1])

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7],
       [0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]])

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6],
       [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]])

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]])

array([[0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1],
       [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1],
       [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1],
       [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1],
       [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1]])

Make initial values for the conductance.

In [9]:
resistor_grid = np.zeros((x_size, y_size, 2,), dtype=np.float64)
resistor_grid[:] = 1
display(resistor_grid[:, :, 0], resistor_grid[:, :, 1])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Reduce the conductance values by cut out a square.

In [10]:
x_lim_low, x_lim_high = 0.0, 0.4
y_lim_low, y_lim_high = 0.3, 0.8
# resistor_grid[(x_lim_low <= x_lgrid) & (x_lgrid <= x_lim_high) & (y_lim_low <= y_lgrid) & (y_lgrid <= y_lim_high)] = 0
overlap_x_size = np.minimum(x_lgrid + a/2, x_lim_high) - np.maximum(x_lgrid - a/2, x_lim_low)
overlap_y_size = np.minimum(y_lgrid + a/2, y_lim_high) - np.maximum(y_lgrid - a/2, y_lim_low)
overlap_x_size[overlap_x_size < 0] = 0
overlap_y_size[overlap_y_size < 0] = 0
resistor_grid -= (overlap_x_size * overlap_y_size) / a**2

In [11]:
display(resistor_grid[:, :, 0], resistor_grid[:, :, 1])

array([[1.00000000e+00, 1.00000000e+00, 3.33066907e-16, 3.33066907e-16,
        5.00000000e-01, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 5.55111512e-16, 5.55111512e-16,
        5.00000000e-01, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+

array([[1.00000000e+00, 7.50000000e-01, 5.00000000e-01, 5.00000000e-01,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 5.00000000e-01, 2.22044605e-16, 2.22044605e-16,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 7.50000000e-01, 5.00000000e-01, 5.00000000e-01,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+

In [12]:
def calc_resistance(resistor_grid, in_set, out_set, *, total_iter=20001, print_every_iter=1000, dt=1/4):
    """
    resistor_grid.shape == (x_size, y_size, 2,)
    current_grid[x, y, 0] == current from (x,y) to (x+1,y)
    current_grid[x, y, 1] == current from (x,y) to (x,y+1)
    voltage[in_set] = 1.0
    voltage[out_set] = 0.0
    current_grid[x, y, 0] = (voltage[x, y] - voltage[x + 1, y]) * resistor_grid[x, y, 0]
    current_grid[x, y, 1] = (voltage[x, y] - voltage[x, y + 1]) * resistor_grid[x, y, 1]
    #
    Only need resistor_grid[:-1, :, 0] and resistor_grid[:, :-1, 1]
    #
    R = rho * L / S
    resistor_grid = 1 / rho # value of resistor_grid is actually conductance.
    """
    x_size, y_size, n_dim = resistor_grid.shape
    voltage = np.zeros((x_size, y_size,), dtype=np.float64)
    voltage[:] = 0.5
    voltage[in_set] = 1.0
    voltage[out_set] = 0.0
    for i in range(total_iter):
        current_grid = np.zeros((x_size, y_size, 2,), dtype=np.float64)
        current_grid[:-1, :, 0] = (voltage[:-1, :] - voltage[1:, :]) * resistor_grid[:-1, :, 0]
        current_grid[:, :-1, 1] = (voltage[:, :-1] - voltage[:, 1:]) * resistor_grid[:, :-1, 1]
        charge_change = np.zeros((x_size, y_size,), dtype=np.float64)
        charge_change[:-1, :] -= dt * current_grid[:-1, :, 0]
        charge_change[1:, :] += dt * current_grid[:-1, :, 0]
        charge_change[:, :-1] -= dt * current_grid[:, :-1, 1]
        charge_change[:, 1:] += dt * current_grid[:, :-1, 1]
        total_current_in = np.sum(charge_change[in_set]) / dt
        total_current_out = np.sum(charge_change[out_set]) / dt
        resistance_from_in = -1.0 / total_current_in
        resistance_from_out = 1.0 / total_current_out
        charge_change[in_set] = 0.0
        charge_change[out_set] = 0.0
        voltage += charge_change
        if i % print_every_iter == 0:
            print(i, np.linalg.norm(charge_change), resistance_from_in, resistance_from_out)
            # display(voltage)
    resistance = (resistance_from_in + resistance_from_out) / 2
    return resistance

In [13]:
%%time
calc_resistance(resistor_grid, in_set, out_set)

0 0.39528470752104744 0.4 0.4
1000 2.991293220029535e-12 2.443866159556622 2.4438661591224093
2000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
3000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
4000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
5000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
6000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
7000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
8000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
9000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
10000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
11000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
12000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
13000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
14000 1.6733576151097032e-16 2.4438661593735804 2.4438661593735667
15000 1.6733576151097032e-16 2.443866159373

2.4438661593735738